version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/base:2023.02
    working_directory: ~/workspace

commands:
  install-python:
    steps:
      - run:
          name: Install Python and dependencies
          command: |
            sudo apt update
            sudo apt install python3.10 -y
            sudo apt install python3-pip -y
            sudo pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt

  install-flake8:
    steps:
      - run:
          name: Install flake8
          command: |
            pip3 install flake8
            pip3 uninstall pyreadline

  install-isort:
    steps:
      - run:
          name: Install isort
          command: pip3 install isort

  install-black:
    steps:
      - run:
          name: Install black
          command: pip3 install black

  install-pylint:
    steps:
      - run:
          name: Install pylint
          command: pip3 install pylint

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - install-python

  flake8:
    executor: python-executor
    steps:
      - checkout
      - install-python
      - install-flake8
      - run:
          name: Run flake8
          command: python3 -m flake8 .

  isort:
    executor: python-executor
    steps:
      - checkout
      - install-python
      - install-isort
      - run:
          name: Run isort
          command: isort .

  black:
    executor: python-executor
    steps:
      - checkout
      - install-python
      - install-black
      - run:
          name: Run black
          command: python3 -m black .

  pylint:
    executor: python-executor
    steps:
      - checkout
      - install-python
      - install-pylint
      - run:
          name: Run pylint
          command: python3 -m pylint ./src/

workflows:
  build:
    jobs:
      - build
      - flake8
      - isort
      - black
      - pylint
